stages:
  - test
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

test:
  image: golang:1.19
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

build:
  stage: build
  image: docker:20.10.9
  services:
    - docker:dind
  script:
    - docker build --pull --rm -f Dockerfile -t blacklist-dev .

deploy:
  stage: deploy
  image: docker:20.10.9
  services:
    - docker:dind
  before_script:
    - apk update
    - apk upgrade
    - apk add curl jq python3 python3-dev build-base libffi-dev libressl-dev gettext
    - curl -O https://bootstrap.pypa.io/get-pip.py
    - python3 get-pip.py
    - pip install docker-compose
  variables:
    - SERVER_PORT=$SERVER_PORT
  script:
    - docker-compose up -d